### ISSUE TITLE
annotations/genomegitar/GSM1267200_DI/DI_sort.bed doesn't contain chr22, chrX and chrY

### ISSUE THREAD

**Issue by Sasha-Barisic** [kircherlab/CADD-SV#15]
My question is based on the heading, will it be possible to include these in that file or is there another work around it? Thanks and much appreciated!

**Comment by CatonaO** [comment]
Hi,
Thank you for your feedback, I just updated the repository and dependencies and genomegitar DI_sort.bed files now include chr22, X and Y. For this fix to work effectively please download the dependencies again, instead of just pulling the git repository to update, also remove the run.caddsv environment and create it again from the updated "environment.yaml".
Best,
Orazio
