### ISSUE TITLE
ChrY converted to ChrX in scoring.R

### ISSUE THREAD

**Issue by TessavdV** [kircherlab/CADD-SV#19]
Hi CADD-SV team, 

I have an issue with the retention of variants located on the Y-chromosome. My input contains 67 variants on the Y-chromosome, and they are still presented as such in matrix.bed, but in {samplename}_score.bed they are presented as ChrX-variants, with all other information (like location) remaining the same. So the only change is where column 1 previously said 'chrY' in matrix.bed, it says 'X' in the final output file. Since this file conversion happens in the rule 'scoring', which executes scoring.R, it might be happening there. Besides this, the variants still seem to be scored correctly. I didn't see a related git-issue, but if you've heard of this issue before, or have an idea as to why this happens, i'd be very gratefull for any assistance. 

Besides this the tool runs smoothly. I'd like to thank you on the very interesting algorithm and any help you can provide on this issue. 
Many thanks, 
Tessa

**Comment by CatonaO** [comment]
Hi Tessa,

Thank you for bringing this to our attention, and thank you for using the tool!
The issue was in the scoring.R script as you pointed out and should be fixed now, so please pull the latest version and retry your analysis. Also a small reminder to interpret results on sex chromosomes with caution given that they are not used in training.

Thank you again for identifying this issue, and please let us know if you run into anything else.

Best,
Orazio

**Comment by TessavdV** [comment]
Hi Orazio, 

Thank you for the quick response! I pulled it and the Y-chromosomes are now present in the end-results, so this fix works. 
I'll do my own subanalysis to see how CADDSV ranks variants we've allready confirmed as causal / pathogenic, thank you for the warning and honesty. 

Best, 
Tessa
